CONFIGURATION:
  DEB_BUILD_DIR: ~/acuda_repomngr_data/deb_build_dir
  DEB_CONTROL_TEMPLATE: |
    Package: ${PACKAGE_NAME}
    Version: ${PACKAGE_VERSION}
    Section: ${PACKAGE_SECTION}
    Priority: ${PACKAGE_PRIORITY}
    Architecture: ${PACKAGE_ARCHITECTURE}
    Depends: ${PACKAGE_DEPENDENCIES}
    Maintainer: ${PACKAGE_MAINTAINER}
    Homepage: ${PACKAGE_HOMEPAGE}
    Description: NO OFFICIAL PACKAGE ${PACKAGE_DESCRIPTION}
  DEB_CONTROL_DEFAULTS:
    PACKAGE_SECTION: misc
    PACKAGE_PRIORITY: optional
    PACKAGE_ARCHITECTURE: amd64
    PACKAGE_DEPENDENCIES: ''
    PACKAGE_HOMEPAGE: ''
    PACKAGE_DESCRIPTION: ''
  REPO_BUILD_DIR: ~/acuda_repomngr_data/rebo_build_dir
  REPO_DISTRIBUTIONS_TEMPLATE: |
    Origin: Acuda
    Label: Acuda Github
    Suite: stable
    Codename: xenial
    Architectures: amd64
    Components: main
    Description: TBD
  REPO_CODENAME: xenial
  APT_LOCAL_TEMPLATE: |
    deb file://${REPO_BUILD_DIR}/ ${REPO_CODENAME} main
MAINTAINER:
 beistel: &beistel
  PACKAGE_MAINTAINER: Björn Eistel <eistel@gmail.com>
 default:
    <<: *beistel
PACKAGES:
- PACKAGE_NAME: acurep
  PACKAGE_VERSION: 0.0.1
  SRC_RELATIVE_TO: /home/beistel/PycharmProjects
  DST_RELATIVE_TO: /opt
  FILES:
  - acuda_repomngr
  LINKS:
  - TARGET: /opt/acuda_repomngr/acurep.py
    NAME: /usr/local/bin/acurep
- PACKAGE_NAME: acuda-i3-config
  PACKAGE_VERSION: 0.0.1
  SRC_RELATIVE_TO: ~/
  DST_RELATIVE_TO: /opt/acuda/config/
  FILES:
  - .i3/config
- PACKAGE_NAME: acuda-scripts
  PACKAGE_VERSION: 0.0.1
  PACKAGE_DEPENDENCIES: acuda-dmenu-system-exit
- PACKAGE_NAME: acuda-dmenu-system-exit
  PACKAGE_VERSION: 0.0.1
  SRC_RELATIVE_TO: ~/installed/system
  DST_RELATIVE_TO: /opt/acuda/scripts
  FILES:
  - dmenu_system_exit.sh
- PACKAGE_NAME: acuda-hhn-ros
  PACKAGE_VERSION: 0.0.1
  PACKAGE_DEPENDENCIES: ros-kinetic-desktop-full
- PACKAGE_NAME: acuda-hhn-ws-systemconnection-hhn
  PACKAGE_VERSION: 0.0.1
  FILES:
  - /etc/NetworkManager/system-connections/HHN
